version: '3.5'
services:
  db:
    image: "postgres"
    container_name: pitang-database
    restart: always
    ports:
      - "5432:5432"    
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pitangdb
  app:    
    container_name: pitang-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/pitangdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: docker
    volumes:
      - "./:/app"
      - ~/.m2:/root/.m2
    working_dir: "/app"  
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db